[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sintrop"
authors = [{name = "Sintrop", email = "sintrop@email.com"}]
dynamic = ["version", "description"]
